name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preheat iOS Simulator
        uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 16e'
          os_version: '=26.2'

      - name: Run unit tests
        run: |
          xcodebuild \
            -project TORoundedButtonExample.xcodeproj \
            -scheme TORoundedButtonTests \
            -destination 'platform=iOS Simulator,name=iPhone 16e,OS=26.2' \
            clean test
